# Generated by Django 2.2.28 on 2022-12-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresssnisywhnrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresssnisywhnrf',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
